- download/download.adoc
- index.html.haml
Added docker community images information in home and downloads pages.
> Added docker community images information.

- _layouts/upgradeRecipeBase.html.haml
- _partials/productToProjectVersionMapping.html.haml
- download/upgradeRecipe/index.adoc
- download/upgradeRecipe/upgradeRecipe7.0.adoc
- website/jBPMWebsite.css
- website/jBPMWebsite.js
@krisv or @mbiarnes could you please review? It's very much the same I did for drools-website recently.
> Start with 6.5 -> 7.0 upgrade recipe

- _config/pom.yml
@krisv please check the installer and installer-full before merging this
> upgraded to 7.2.0.Final

- _config/pom.yml
- code/continuousIntegration.adoc
- learn/documentation.adoc
feel free to merge when its green - it gets automatically published
> upgrade to 7.7.0.Final

- download/download.adoc
feel free to merge it once it is green and you approved it
> JBPM-7131:replaced hard coded docker version by variable

- _layouts/base.html.haml
- _layouts/blogBase.html.haml
- code/sourceCode.adoc
- community/getHelp.html.haml
- community/governance.adoc
- index.html.haml
- Fixed broken links
- Refined get help section
> Updates to website

- api-docs/definitions.adoc
- api-docs/paths.adoc
- api-docs/swagger.json
@tsurdilo @cristianonicolai update to api-docs to look more accessible
> updated api docs to include ToC and small updates to examples

- _config/importantNews.yml
- _config/pom.yml
- learn/releasenotes/7-15-0.adoc
- learn/releases.html.haml
@mbiarnes here are the updates for 7.15 release
> updates for 7.15 release

- api-docs/controller/overview.adoc
- api-docs/controller/paths.adoc
- api-docs/controller/swagger.json
Please wait until https://github.com/kiegroup/droolsjbpm-integration/pull/1646 is merged.
> [do not merge] JBPM-7934 - Swagger Controller updates

- api-docs/controller/paths.adoc
- api-docs/controller/swagger.json
Related to https://github.com/kiegroup/droolsjbpm-integration/pull/1686
> JBPM-7934 - Add examples to path parameters

- learn/releasenotes/7-16-0.adoc
Related to https://github.com/kiegroup/kie-docs/pull/1351
> Release notes fixes

- _config/importantNews.yml
- _config/pom.yml
- learn/releasenotes/7-17-0.adoc
- learn/releases.html.haml
@mbiarnes @cristianonicolai can anyone of view have a look?
> jbpm website updates for 7.17 release

- learn/jbpmPerformance.html.haml
Improving readability by adjusting headers weight. Slight adjusts on the text.
> Adjusting some styling and text details from jbpmPerformance page

- api-docs/controller/paths.adoc
- api-docs/controller/swagger.json
Depends on https://github.com/kiegroup/droolsjbpm-integration/pull/1778
> Controller Swagger docs update

- community/getHelp.html.haml
Hi,
I had some issues with `Mibbit` online IRC client (I wasn't able to connect to it using Firefox on Linux).  So, I found, tested and added one more alternative.
P.S. Inspired by user question on [StackOverflow](https://stackoverflow.com/questions/58369719/how-to-use-or-run-jbpm-designer).
> Add addition online IRC client

- api-docs/kie-server/definitions.adoc
- api-docs/kie-server/overview.adoc
- api-docs/kie-server/paths.adoc
- api-docs/kie-server/swagger.json
Generated new adoc files with kie-server services to cover new `scesim` endpoint. The diff is bigger than expected so I guess this doc has not been updated since a while
@mswiderski @kaldesai @sterobin 
https://issues.redhat.com/browse/DROOLS-4947
> [DROOLS-4947] Test Scenario: update kie-server swagger API doc 

- api-docs/kie-server/swagger.json
Changes in Swagger related with JIRA  https://issues.redhat.com/browse/BAPL-1575
> [BAPL-1575] Updating swagger file after Task API changes

- index.html.haml
It is not so easy to know the login and password for the quick test, after my change it should be simplified:
> Add login/password information for the quick login

- api-docs/kie-server/swagger.json
__JIRA__ :  [JBPM-9410](https://issues.redhat.com/browse/JBPM-9410)
Updated swagger.json after adding schema (where missing) to successful responses in GET, POST methods.
> [JBPM-9410] No Model definition in KIE Server Swagger API.

- _config/importantNews.yml
- _config/pom.yml
- download/download.html.haml
- updated to 7.49.0.Final release
- modified updatesite link to point to the latest released version 7.48.0.Final
> updated to 7.49.0.Final

- download/download.html.haml
@cristianonicolai Please merge right away when you're OK with this.
> put Eclipse update site in an own passage

- _config/importantNews.yml
- _config/pom.yml
the website still works with Rake and the Jenkins job: [jbpm-automatic-web-publishing](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/webs/job/jbpm-automatic-web-publishing/)
It was not yet moved to use JBake.
When this PR is merged it will trigger the job.
Important: please assure that merging this will not interfere into the work Jason is doing!
> upgraded to 7.55.0.Final

- _layouts/base.html.haml
ref https://github.com/kiegroup/drools-website/pull/166
preview
> Add footer link to Kogito

- _layouts/base.html.haml
- _layouts/blogBase.html.haml
- _layouts/normalBase.html.haml
- _layouts/upgradeRecipeBase.html.haml
- _partials/blogPostBody.html.haml
- _partials/events.html.haml
- _partials/importantNews.html.haml
- _partials/latestBlogPosts.html.haml
- _partials/latestTweets.html.haml
- _partials/referencesBooks.html.haml
- community/getHelp.html.haml
- download/download.html.haml
- index.html.haml
- learn/gettingStarted.html.haml
- learn/jbpmPerformance.html.haml
- learn/releases.html.haml
- product/services.html.haml
- website/jBPMWebsite.css
- website/jBPMWebsite.js
Just Bootstrap 5 changes. Once we get these merged, I'll start on jbake changes, but we'll want to freeze the site while that happens.
> Bootstrap 5 migration

- _dockerPublisher/Dockerfile
updated docker file to fedora 34 and stabilized it
> Dockerfile

- Rakefile.rb
https://github.com/kiegroup/jbpm-website/pull/195
https://github.com/kiegroup/kie-jenkins-scripts/pull/1244
this PR(s) fix the rsync as user jbpm to filemgmt-prod-sync-jboss.org and with this the automatic publishing of the jbpm-website
> fixed automatic web publishing

- templates/_content_businessapps_gettingStarted.ftl
This PR fixes a link in the Getting Started page.
> Fixed link
